tests_include:
  - test_rpc_version
  - test_interface

test_rpc_version:
  - rpc: get-config
  - kwargs:
      filter_xml: configuration/system/login
  - item:
      xpath: //configuration
      tests:
        - is-equal: //minimum-time, 60
          info: "Test Succeeded!!, minimum-time now is equal to <{{post['//minimum-time']}}>"
          err: "Test Failed!!!, minimum-time is not equal to 60, it is <{{post['//minimum-time']}}>"

test_interface:
  - rpc: get-interface-information
    #format: text
  - kwargs:
      interface-name: em0
      media: True
      detail: True
  - item:
      xpath: //physical-interface
      tests:
        - is-gt: snmp-index, 2
          info: "Test Succeeded!!, snmp-index is greater than 2, it is <{{post['snmp-index']}}>"
          err: "Test Failed!!!, snmp-index is not greater than 2, it is <{{post['snmp-index']}}>"
